# Generated by Django 3.2.16 on 2023-01-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0027_auto_20230116_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('image', models.FileField(blank=True, upload_to='about_us')),
                ('image_title', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='Education')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('icon', models.FileField(blank=True, upload_to='icon/Education')),
                ('icon_title', models.CharField(blank=True, max_length=200)),
                ('hyperlink', models.CharField(blank=True, max_length=500)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Header_logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to='photo/Header')),
                ('hyperlink', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Header_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.CharField(blank=True, max_length=100)),
                ('hyperlink', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Interviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('icon', models.FileField(blank=True, upload_to='interviews')),
                ('icon_title', models.CharField(blank=True, max_length=500)),
                ('hyperlink', models.CharField(blank=True, max_length=600)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='what_we_do',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='What_we_do/about_us')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
